# Name: Anirudh S
# Roll no: CS17B003

all: sr gbn
sr: sendsr recsr
gbn: sendgbn recgbn

sendsr: SenderSR.java
	javac SenderSR.java

recsr: ReceiverSR.java
	javac ReceiverSR.java

sendgbn: SenderGBN.java
	javac SenderGBN.java

recgbn: ReceiverGBN.java
	javac ReceiverGBN.java

clean:
	rm *.class